# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-27 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0048_project_specific_id_null'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datasource',
        ),
    ]
